WebProject/WebProject/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.dbEntities;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class CartController : Controller
    {
        Product_ManagermentEntities obj = new Product_ManagermentEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
       
        public ActionResult AddToCart(string id, int quantity)
        {
            //Session["pay"] = request.Form["Fruit"];
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = obj.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
              
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = obj.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(string id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.BARCODE.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(string Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.BARCODE == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

WebProject/WebProject/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProject.dbEntities;
using WebProject.Models;

namespace WebProject.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        Product_ManagermentEntities objproduct = new Product_ManagermentEntities();
        public ActionResult Index()
        {
            if(Session["idCustom"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                var lstCar = (List < CartModel >) Session["cart"];
                Order obj = new Order();
                obj.NameProduct = "Đon hàng" + DateTime.Now.ToString("yyyyMMddmmss");
                obj.idCus = Session["idCustom"].ToString();

                obj.pay = "Tiền Mặt";
                obj.CreateOrder = DateTime.Now;
               
                obj.Status = true;
                objproduct.Orders.Add(obj);

                objproduct.SaveChanges();

                int id = obj.idOrder;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();
                foreach(var item in lstCar)
                {
                    OrderDetail objdetail = new OrderDetail();
                    objdetail.Quantity = item.Quantity;
                    objdetail.OrderId = id;
                    objdetail.ProductId = item.Product.BARCODE;

                    lstOrderDetail.Add(objdetail);
                }
                objproduct.OrderDetails.AddRange(lstOrderDetail);
                objproduct.SaveChanges();
                Session["count"] = 0;
            }
            return View();
        }
       
    }
}

WebProject/WebProject/Views/Cart/Index.cshtml
@model IEnumerable<WebProject.Models.CartModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                   
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>

                                <th scope="col" width="120"> Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr id="product-@item.Product.BARCODE">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/12.jpg" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.NameAT</a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <var class="quantity">@item.Quantity</var>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@item.Product.Price</var>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@(item.Product.Price*item.Quantity)</var>
                                            </div>
                                        </td>

                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.BARCODE" id="productid" />

                                            <a href="" class="btn btn-light" id="removecart"> Remove</a>




                                        </td>

                                    </tr>


                                }
                            }
                            else
                            {
                                <p>Không có sản phẩm trong giỏ hàng</p>
                            }


                        </tbody>
                    </table>


                    <div class="card-body border-top">
                        <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right">Thanh toán<i class="fa fa-chevron-right"></i></a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"><i class="fa fa-chevron-left"></i>Tiếp tục mua sắm</a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
                </div>

            </main> <!-- col.// -->

            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form id="tmp" runat="server">
                            <div class="form-group">
                                <label>Chọn Phương Thức Thanh Toán</label>
                                <div class="input-group">
                                    <select class="form-control" name="Fruit" required>
                                      
                                        <option value="Tiền Mặt">Tiền Mặt</option>
                                    </select>
                                    <br />
                                    <br />
                                  

                                    @*<span class="input-group-append">
            <button class="btn btn-primary">Đồng ý</button>
        </span>*@
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>
    

    </div> <!-- container .//  -->

</section>